Repository KrlosPK/algora-ct, pull requests merged in 2024-03, with the labels that each got.

#1 Create `Layout.astro` in `index.astro` with Typography test
  src/components/atoms/Head.astro
  src/components/atoms/Typography.astro
  src/layouts/Layout.astro
  src/pages/index.astro
Labels: enhancement, help wanted

#2 Add MetaData component into Layout and component name change to `Meta Data`
  src/components/atoms/MetaData.astro
  src/layouts/Layout.astro
Labels: enhancement

#4 Colores del proyecto añadidos
  src/layouts/Layout.astro
  tailwind.config.mjs
Labels: help wanted

#6 Fix - a tailwind extend class for colors errors with text-base class
  tailwind.config.mjs
Labels: help wanted

#5 "features" section finished, it can be improved
  .vscode/settings.json
  public/AI.svg
  public/addUser.svg
  public/shareWord.svg
  src/components/atoms/Typography.astro
  src/components/sections/Features.astro
  src/layouts/Layout.astro
  src/pages/index.astro
Labels: enhancement

#7 Sección "Hero" agregada al index.astro
  src/components/atoms/Action.astro
  src/components/atoms/Typography.astro
  src/components/organism/Card.astro
  src/components/organism/Navbar.astro
  src/components/sections/Hero.astro
  src/pages/index.astro
Labels: enhancement

#8 Modificación de la altura en la sección del hero
  src/pages/index.astro
Labels: enhancement

#11 Formulario de inicio de sesión básico y configuraciones requeridas
  .eslintignore
  .eslintrc.cjs
  .vscode/settings.json
  astro.config.mjs
  package.json
  pnpm-lock.yaml
  src/components/organism/Form.svelte
  src/layouts/Layout.astro
  src/pages/api/login.ts
  src/pages/index.astro
  src/pages/login/index.astro
  svelte.config.js
  tailwind.config.mjs
Labels: enhancement
